### ISSUE TITLE
Every number "56" is delete of the string

### ISSUE THREAD

**Issue by EnriqueER** [hamedpa/perfect-express-sanitizer#10]
Hello good mornign.

I started to use your module in Nodejs and everything works fine but I just noticed that if you put the numbre "56" is deleted, for example if some telefon number like this "55-56-89-85" is set to be sanitized the number "56" will be deleted.

```
var perfectExpressSanitizer = require("perfect-express-sanitizer")

let elementClean = perfectExpressSanitizer.sanitize.prepareSanitize("55-56-89-85", { xss: true, noSql: true, sql: true, level: 5 });

console.log(elementClean)
```
OUTPUT: "5589-85"

Maybe I am doing something wrong?

**Comment by pariazar** [comment]
Hello
thanks for your helpful comment,
you're right, there was a problem when input has 56 number that fixed in new version 1.0.10
