### ISSUE TITLE
allowedKeys not working

### ISSUE THREAD

**Issue by FeHuynhVI** [hamedpa/perfect-express-sanitizer#15]
app.use(sanitizer.clean({
  xss: true,
  noSql: true, level: 5,
  allowedKeys: ['p', 'a', 'img']
}));

**Comment by SFaraji** [comment]
allowedKeys doesn't work for me either. Can someone look into this. 
Thanks,

**Comment by pariazar** [comment]
The issue has been successfully resolved in the latest version 2.0.0

**Comment by bunyaminmrcn** [comment]
Not working with latest version(2.0.2)
